spring:
  application:
    name: forum-backend
  output:
    ansi:
      enable: ALWAYS
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false
    username: root
    password: 8888
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: NON_NULL

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    
mybatis:
  mapper-location: classpath:mapper/**/*.xml

server:
  port: 8080

login:
  url: /sign-in.html

index:
    board-num: 9 #首页显示的板块数


# Springdoc OpenAPI 配置
springdoc:
  # 扫描哪些包里的 Controller 来生成文档
  packages-to-scan: com.weisizhang.forumbackend.controller
  swagger-ui:
    # Swagger UI 页面的访问路径
    path: /swagger-ui.html
  api-docs:
    # OpenAPI JSON 文档的访问路径（可导入 Postman）
    path: /v3/api-docs

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true


logging:
  pattern:
    dateformat: HH:mm:ss
  level:
    root: info
    com.weisizhang.forumbackend: debug
  file:
    path: ./log/project/forum
